### ISSUE TITLE
Provide step size information for inpect mode

### ISSUE THREAD

**Issue by kevinksyTRD** [open-simulation-platform/cosim-cli#68] opened 2020-05-27 12:57 UTC
I would like to have the step size information of an fmu from the cli inspect mode so that I can provide the information to a user in case he/she would like to change the value for a simulator.

**Comment by kyllingstad** [comment] 2020-06-22 05:48
Closing, as this seems to be a duplicate of #52.

**Closed by kyllingstad** 2020-06-22 05:48 UTC
Labels: duplicate
